version: '3'
services:

  app:
    build: .
    env_file: .env
    working_dir: /opt/app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/app
    depends_on:
      - postgresql
    networks:
      - service
    ports:
      - "8000:8000"

  postgresql:
    image: postgres:14-alpine
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
    volumes:
      - pgsql:/var/lib/postgresql/data
    networks:
      - service

networks:
  service:
    driver: bridge

volumes:
  pgsql:
    driver: local